Resources:
  MyECSCluster:
    Type: AWS::ECS::Cluster
  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      TaskDefinition: arn:aws:ecs:us-west-2>:315414901942:task-definition/sams-collectibles-task