AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for CloudFormation to deploy resources

Resources:
  CloudFormationResourcePermissions:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationResourcePermissions
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
                