# Generated by Django 4.2.16 on 2026-04-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ebay_item_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ebay_listing_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('category_id', models.CharField(blank=True, max_length=10, null=True)),
                ('condition_id', models.CharField(blank=True, max_length=5, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Submission'), ('active', 'Active on eBay'), ('sold', 'Sold'), ('ended', 'Ended'), ('error', 'Error')], default='draft', max_length=20)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('item_specifics', models.JSONField(blank=True, default=dict)),
                ('shipping_service', models.CharField(default='USPSPriority', max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('returns_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ebay_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('buyer_username', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('ebay_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('payment_status', models.CharField(blank=True, max_length=30, null=True)),
                ('creation_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_service', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ebay_orders',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='EbayOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ebay_manager.ebaylisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ebay_manager.ebayorder')),
            ],
            options={
                'db_table': 'ebay_order_items',
            },
        ),
    ]
