# Generated by Django 4.2.16 on 2026-04-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ebay_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaylisting',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
