# Generated by Django 4.2.16 on 2026-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0002_alter_ebaylisting_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaylisting',
            name='ebay_listing_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
