# Generated by Django 4.2.16 on 2026-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0003_alter_ebaylisting_ebay_listing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='weight_lbs',
            field=models.IntegerField(default=0, help_text='Product weight - pounds'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='weight_oz',
            field=models.IntegerField(default=0, help_text='Product weight - ounces'),
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='shipping_service',
            field=models.CharField(default='USPSGroundAdvantage', max_length=50),
        ),
    ]
