# Generated by Django 4.2.16 on 2026-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0004_ebaylisting_weight_lbs_ebaylisting_weight_oz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='packaging_config',
            field=models.CharField(choices=[('sealed_box', 'Sealed Wax Box'), ('raw_stacked', 'Raw Stacked Cards (6x4x2)'), ('9_pocket_single', '9-Pocket Sheets Single Set (13x10x2)'), ('9_pocket_multi', '9-Pocket Sheets Multiple Sets (13x10x3)'), ('custom', 'Custom / Other')], default='sealed_box', help_text='Determines box size, packaging weight, and shipping policy', max_length=20),
        ),
    ]
