# Generated by Django 4.2.16 on 2026-04-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0005_ebaylisting_packaging_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='package_height',
            field=models.IntegerField(default=0, help_text='Package height in inches'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='package_length',
            field=models.IntegerField(default=0, help_text='Package length in inches'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='package_width',
            field=models.IntegerField(default=0, help_text='Package width in inches'),
        ),
    ]
