# Generated by Django 4.2.16 on 2026-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0006_ebaylisting_package_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='market_mean_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Top quartile mean of active eBay listings for similar items', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market mean minus $1.05 (target selling price)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='packaging_config',
            field=models.CharField(choices=[('sealed_box', 'Cardboard Box'), ('raw_stacked', 'Raw Stacked Cards (6x4x2)'), ('9_pocket_single', '9-Pocket Sheets Single Set (13x10x2)'), ('9_pocket_multi', '9-Pocket Sheets Multiple Sets (13x10x3)'), ('custom', 'Custom / Other')], default='sealed_box', help_text='Determines box size, packaging weight, and shipping policy', max_length=20),
        ),
    ]
