# Generated by Django 4.2.16 on 2026-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0007_ebaylisting_market_mean_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text='eBay inventory item group key — ties variants together', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='is_variant',
            field=models.BooleanField(default=False, help_text='True if this listing is part of a multi-variant group'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='parent_r2_prefix',
            field=models.CharField(blank=True, help_text='Parent R2 folder for variant groups (e.g. trading-cards/boxes/space-1999)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Variant display name (e.g. "Box 1", "Box 2")', max_length=50, null=True),
        ),
    ]
