# Generated by Django 4.2.16 on 2026-04-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_manager', '0008_ebaylisting_group_key_ebaylisting_is_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_prefix', models.CharField(help_text='Full R2 path e.g. trading-cards/sets/star-wars/a-new-hope-77/series-1/mixed/103', max_length=300, unique=True)),
                ('group_key', models.CharField(blank=True, help_text='EbayListing variant group key if linked', max_length=50, null=True)),
                ('series', models.CharField(blank=True, help_text='Series name e.g. series-1', max_length=50, null=True)),
                ('set_number', models.CharField(blank=True, help_text='Set number e.g. 103', max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('total_cards', models.IntegerField(default=66, help_text='Expected card count for this series')),
                ('scanned_cards', models.IntegerField(default=0)),
                ('single_star_count', models.IntegerField(default=0, help_text='Cards with ★')),
                ('double_star_count', models.IntegerField(default=0, help_text='Cards with ★★')),
                ('unknown_count', models.IntegerField(default=0, help_text='Cards that could not be read')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'card_set_scan_status',
                'ordering': ['r2_prefix'],
            },
        ),
        migrations.CreateModel(
            name='CardAsteriskScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(help_text='Card number (1-66 for Series 1)')),
                ('asterisk_count', models.IntegerField(default=0, help_text='1 for ★, 2 for ★★, 0 for unknown/unreadable')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0.0-1.0 from Claude analysis')),
                ('page_number', models.IntegerField(help_text='Photo page number (1-16)')),
                ('position', models.IntegerField(help_text='Position in 9-pocket page (1-9)')),
                ('card_title', models.CharField(blank=True, help_text='Card title text e.g. "Rebels defend their starship!"', max_length=200, null=True)),
                ('image_crop_url', models.CharField(blank=True, help_text='R2 URL of the cropped card image', max_length=500, null=True)),
                ('raw_response', models.TextField(blank=True, help_text='Raw Claude API response for debugging', null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ebay_manager.setscanstatus')),
            ],
            options={
                'db_table': 'card_asterisk_scans',
                'ordering': ['scan_set', 'card_number'],
                'unique_together': {('scan_set', 'card_number')},
            },
        ),
    ]
