# Generated by Django 4.2.16 on 2024-09-13 20:28

from django.db import migrations, models
import non_sports_cards.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NonSportsCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                ("date_manufactured", models.CharField(max_length=4)),
                ("description", models.TextField()),
                (
                    "key_features",
                    models.JSONField(
                        default=list,
                        validators=[non_sports_cards.models.validate_key_features],
                    ),
                ),
            ],
        ),
    ]
