# Generated by Django 4.2.16 on 2024-09-14 22:19

from django.db import migrations, models
import django.db.models.deletion
import non_sports_cards.models


class Migration(migrations.Migration):
    dependencies = [
        ("non_sports_cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonSportsCardsBaseSets",
            fields=[
                (
                    "nonsportscards_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsportscards_base_sets",
            },
            bases=("non_sports_cards.nonsportscards",),
        ),
        migrations.CreateModel(
            name="NonSportsCardsBoxes",
            fields=[
                (
                    "nonsportscards_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsportscards_boxes",
            },
            bases=("non_sports_cards.nonsportscards",),
        ),
        migrations.CreateModel(
            name="NonSportsCardsSpecialSets",
            fields=[
                (
                    "nonsportscards_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsportscards_special_sets",
            },
            bases=("non_sports_cards.nonsportscards",),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="number_of_cards_in_a_set",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="number_of_cards_per_pack",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="number_of_packs_per_box",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="number_of_sets_per_box",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="date_manufactured",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="key_features",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                validators=[non_sports_cards.models.validate_key_features],
            ),
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="nonsportscards",
            table="nonsportscards",
        ),
        migrations.CreateModel(
            name="NonSportsSpecialCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "special_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Promo", "Promo Cards"),
                            ("LimitedEdition", "Limited Edition Cards"),
                            ("Redemption", "Redemption Cards"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "limited_edition_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nonsportscard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonsports_special_cards",
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsports_special_cards",
            },
        ),
        migrations.CreateModel(
            name="NonSportsInsertCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "insert_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Autographed", "Autographed Cards"),
                            ("Sketch", "Sketch Cards"),
                            ("Relic", "Relic/Memorabilia Cards"),
                            ("Lenticular", "Lenticular/3D Cards"),
                            ("Puzzle", "Puzzle Cards"),
                            ("Costume", "Costume Cards"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nonsportscard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonsports_insert_cards",
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsports_insert_cards",
            },
        ),
        migrations.CreateModel(
            name="NonSportsChaseCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "chase_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Holographic", "Holographic Cards"),
                            ("Foil", "Foil Cards"),
                            ("Embossed", "Embossed Cards"),
                            ("Die-Cut", "Die-Cut Cards"),
                            ("Parallel", "Parallel Cards"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nonsportscard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonsports_chase_cards",
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsports_chase_cards",
            },
        ),
        migrations.CreateModel(
            name="NonSportsCardsSingles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="non_sports_cards.nonsportscardsbasesets",
                    ),
                ),
                (
                    "chase_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="non_sports_cards.nonsportschasecards",
                    ),
                ),
                (
                    "insert_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="non_sports_cards.nonsportsinsertcards",
                    ),
                ),
                (
                    "special_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="non_sports_cards.nonsportsspecialcards",
                    ),
                ),
            ],
            options={
                "db_table": "nonsportscards_singles",
            },
        ),
    ]
