# Generated by Django 4.2.16 on 2024-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "non_sports_cards",
            "0002_nonsportscardsbasesets_nonsportscardsboxes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonsportscards",
            name="number_of_sets_per_box",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
