# Generated by Django 4.2.16 on 2024-09-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("non_sports_cards", "0003_alter_nonsportscards_number_of_sets_per_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonsportscards",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("Topps", "Topps"),
                    ("Fleer", "Fleer"),
                    ("SkyBox", "SkyBox International"),
                    ("Donruss", "Donruss (Pinnacle Brands)"),
                    ("Inkworks", "Inkworks"),
                    ("Rittenhouse Archives", "Rittenhouse Archives"),
                    ("Leaf", "Leaf"),
                    ("Dart Flipcards", "Dart Flipcards"),
                    ("Pacific", "Pacific"),
                    ("Artbox", "Artbox"),
                    ("Cryptozoic", "Cryptozoic Entertainment"),
                    ("Upper Deck", "Upper Deck"),
                    ("Breygent", "Breygent Marketing"),
                    ("Comic Images", "Comic Images"),
                    ("Impel Marketing", "Impel Marketing"),
                    ("Panini", "Panini"),
                    ("Krome", "Krome Productions"),
                    ("Philadelphia Gum", "Philadelphia Gum Company"),
                    ("Brooke Bond", "Brooke Bond"),
                    ("FPG", "FPG (Friedlander Publishing Group)"),
                    ("Marvel Comics", "Marvel Comics"),
                    ("Wizards of the Coast", "Wizards of the Coast"),
                ],
                default="Unknown",
                max_length=255,
            ),
        ),
    ]
