# Generated by Django 4.2.16 on 2024-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("non_sports_cards", "0005_alter_nonsportscards_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonsportscards",
            name="app",
            field=models.CharField(default="ns-cards", max_length=50),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="image_type",
            field=models.CharField(default="sets", max_length=50),
        ),
        migrations.AddField(
            model_name="nonsportscards",
            name="sub_category",
            field=models.CharField(default="Uncategorized", max_length=100),
            preserve_default=False,
        ),
    ]
