# Generated by Django 4.2.16 on 2025-01-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "non_sports_cards",
            "0006_nonsportscards_app_nonsportscards_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nonsportscards",
            name="image_name",
        ),
        migrations.AlterField(
            model_name="nonsportscards",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
        migrations.CreateModel(
            name="NonSportsCardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Back"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("s3_path", models.URLField()),
                (
                    "non_sports_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="non_sports_cards.nonsportscards",
                    ),
                ),
            ],
        ),
    ]
