# Generated by Django 4.2.16 on 2025-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("non_sports_cards", "0007_remove_nonsportscards_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonsportscardimage",
            name="image_type",
            field=models.CharField(
                choices=[("front", "Front"), ("back", "Back"), ("other", "Other")],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nonsportscardimage",
            name="s3_path",
            field=models.URLField(help_text="Full S3 path to the image"),
        ),
        migrations.AlterModelTable(
            name="nonsportscardimage",
            table="nonsportscard_images",
        ),
    ]
