# Generated by Django 4.2.16 on 2025-01-19 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("non_sports_cards", "0008_alter_nonsportscardimage_image_type_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="nonsportscardimage",
            table="nonsportscardimage",
        ),
    ]
