# Generated by Django 4.2.16 on 2025-01-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("non_sports_cards", "0009_alter_nonsportscardimage_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonsportscardimage",
            name="uploaded_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_images",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nonsportscardimage",
            name="image_type",
            field=models.CharField(
                choices=[("front", "Front"), ("back", "Back"), ("other", "Other")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nonsportscardimage",
            name="s3_path",
            field=models.URLField(),
        ),
    ]
