# Generated by Django 4.2.16 on 2026-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0010_nonsportscardimage_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='validation_status',
            field=models.CharField(choices=[('unvalidated', 'Unvalidated'), ('enriched', 'Enriched'), ('verified', 'Verified')], default='unvalidated', max_length=20),
        ),
    ]
