# Generated by Django 4.2.16 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0011_nonsportscards_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='ebay_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
