# Generated by Django 4.2.16 on 2026-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0012_nonsportscards_ebay_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='parent_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='quantity_owned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='series_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='series_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='star_variant',
            field=models.CharField(blank=True, choices=[('1_star', '1 Star'), ('2_star', '2 Star'), ('mixed', 'Mixed Stars'), ('sticker', 'Sticker Set'), ('na', 'N/A')], max_length=20, null=True),
        ),
    ]
