# Generated by Django 4.2.16 on 2026-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0013_nonsportscards_parent_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='custom_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
