# Generated by Django 4.2.16 on 2026-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0015_nonsportscards_post_restoration_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold_out', 'Sold Out'), ('reserved', 'Reserved'), ('listed', 'Listed on eBay')], default='in_stock', max_length=20),
        ),
    ]
