# Generated by Django 4.2.16 on 2026-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0017_nonsportscards_weight_lbs_nonsportscards_weight_oz'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='set_configuration',
            field=models.CharField(blank=True, choices=[('sealed_box', 'Sealed Wax Box'), ('raw_stacked', 'Raw Stacked Cards'), ('9_pocket', '9-Pocket Sheet Pages'), ('binder', 'Binder with Pages'), ('pack', 'Sealed Pack(s)'), ('other', 'Other')], default='sealed_box', help_text='How the cards are stored — affects packaging and shipping', max_length=20),
        ),
    ]
