# Generated by Django 4.2.16 on 2026-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0018_nonsportscards_set_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='market_mean_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Top quartile mean of active eBay listings', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nonsportscards',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market mean minus $1.05', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nonsportscards',
            name='set_configuration',
            field=models.CharField(blank=True, choices=[('sealed_box', 'Cardboard Box'), ('raw_stacked', 'Raw Stacked Cards'), ('9_pocket', '9-Pocket Sheet Pages'), ('binder', 'Binder with Pages'), ('pack', 'Sealed Pack(s)'), ('other', 'Other')], default='sealed_box', help_text='How the cards are stored — affects packaging and shipping', max_length=20),
        ),
    ]
