# Generated by Django 4.2.16 on 2026-04-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_sports_cards', '0019_nonsportscards_market_mean_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsportscards',
            name='condition',
            field=models.CharField(blank=True, choices=[('7000', 'New / Factory Sealed'), ('4000', 'Ungraded'), ('3000', 'Used'), ('2750', 'Graded (Professional)'), ('6000', 'Acceptable')], default='7000', help_text='Item condition for eBay listings', max_length=5),
        ),
    ]
