# Generated by Django 4.2.16 on 2024-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_posters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movieposters",
            name="movie_title",
        ),
        migrations.AddField(
            model_name="movieposters",
            name="condition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movieposters",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movieposters",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movieposters",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
