# Generated by Django 4.2.16 on 2026-04-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_posters', '0002_remove_movieposters_movie_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieposters',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movieposters',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='ebay_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='franchise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='linen_backed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='poster_type',
            field=models.CharField(blank=True, choices=[('original', 'Original Theatrical Release'), ('reissue', 'Re-issue/Re-release'), ('reproduction', 'Reproduction/Reprint'), ('advance', 'Advance/Teaser'), ('special', 'Special Edition'), ('international', 'International'), ('commercial', 'Commercial Print'), ('promo', 'Promotional')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='rolled_or_folded',
            field=models.CharField(blank=True, choices=[('rolled', 'Rolled'), ('folded', 'Folded')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='validation_status',
            field=models.CharField(choices=[('unvalidated', 'Unvalidated'), ('enriched', 'Enriched'), ('verified', 'Verified')], default='unvalidated', max_length=20),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='movieposters',
            name='condition',
            field=models.CharField(blank=True, choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('very_fine', 'Very Fine'), ('fine', 'Fine'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movieposters',
            name='size',
            field=models.CharField(blank=True, choices=[('one_sheet', 'One Sheet (27x41)'), ('half_sheet', 'Half Sheet (22x28)'), ('insert', 'Insert (14x36)'), ('lobby_card', 'Lobby Card (11x14)'), ('mini', 'Mini (varies)'), ('three_sheet', 'Three Sheet (41x81)'), ('six_sheet', 'Six Sheet (81x81)'), ('24x36', 'Standard (24x36)'), ('bus_stop', 'Bus Stop/Subway (varies)'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='movieposters',
            table='movie_posters',
        ),
        migrations.CreateModel(
            name='MoviePosterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('detail', 'Detail/Close-up'), ('other', 'Other')], max_length=50)),
                ('s3_path', models.URLField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movie_posters.movieposters')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_poster_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_poster_images',
            },
        ),
    ]
