# Generated by Django 4.2.16 on 2026-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_posters', '0003_remove_movieposters_release_date_movieposters_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposters',
            name='post_restoration_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='post_restoration_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='pre_restoration_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='pre_restoration_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_priority',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Critical (High Value)'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low'), (5, '5 - Skip')], null=True),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_status',
            field=models.CharField(choices=[('none', 'No Treatment Needed'), ('recommended', 'Recommended'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='restoration_type',
            field=models.CharField(blank=True, choices=[('linen_backing', 'Linen-Backing'), ('tear_repair', 'Tear Repair'), ('color_touch', 'Color Touch-Up'), ('cleaning', 'Cleaning'), ('deacidification', 'Deacidification')], max_length=30, null=True),
        ),
    ]
