# Generated by Django 4.2.16 on 2026-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_posters', '0005_movieposters_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposters',
            name='weight_lbs',
            field=models.IntegerField(default=0, help_text='Weight - pounds'),
        ),
        migrations.AddField(
            model_name='movieposters',
            name='weight_oz',
            field=models.IntegerField(default=0, help_text='Weight - ounces'),
        ),
    ]
