# Generated by Django 4.2.16 on 2024-09-18 20:15

import comic_books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KeyIssueFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("is_key_issue", models.BooleanField(default=False)),
                (
                    "key_facts",
                    models.TextField(
                        blank=True,
                        help_text="Provide details like first appearances, major events (comma-separated).",
                        null=True,
                    ),
                ),
                (
                    "characters_appearing",
                    models.TextField(
                        blank=True,
                        help_text="List of important characters appearing (comma-separated).",
                    ),
                ),
                (
                    "key_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason why this issue is a key issue (comma-separated).",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarWarsMarvelComic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Unknown", max_length=200)),
                ("issue_number", models.IntegerField(default=1)),
                ("release_date", models.DateField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        default=comic_books.models.Publisher.get_unknown_publisher,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comic_books.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("issue_number", "publisher")},
            },
        ),
        migrations.CreateModel(
            name="StarWarsDarkHorseComic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Unknown", max_length=200)),
                ("issue_number", models.IntegerField(default=1)),
                ("release_date", models.DateField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        default=comic_books.models.Publisher.get_unknown_publisher,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comic_books.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("issue_number", "publisher")},
            },
        ),
        migrations.CreateModel(
            name="StarTrekDcComic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Unknown", max_length=200)),
                ("issue_number", models.IntegerField(default=1)),
                ("release_date", models.DateField(null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        default=comic_books.models.Publisher.get_unknown_publisher,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comic_books.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("issue_number", "publisher")},
            },
        ),
    ]
