# Generated by Django 4.2.16 on 2026-04-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startrekdccomic',
            name='condition',
            field=models.CharField(blank=True, choices=[('near_mint_mint', 'NM/M (9.2+)'), ('near_mint', 'NM (9.0-9.2)'), ('very_fine_near_mint', 'VF/NM (8.0-9.0)'), ('very_fine', 'VF (7.0-8.0)'), ('fine_very_fine', 'F/VF (6.0-7.0)'), ('fine', 'Fine (5.0-6.0)'), ('very_good_fine', 'VG/F (4.0-5.0)'), ('very_good', 'VG (3.0-4.0)'), ('good', 'Good (1.8-3.0)'), ('fair', 'Fair (1.0-1.8)'), ('poor', 'Poor (0.5-1.0)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startrekdccomic',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startrekdccomic',
            name='ebay_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startrekdccomic',
            name='validation_status',
            field=models.CharField(choices=[('unvalidated', 'Unvalidated'), ('enriched', 'Enriched'), ('verified', 'Verified')], default='unvalidated', max_length=20),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='condition',
            field=models.CharField(blank=True, choices=[('near_mint_mint', 'NM/M (9.2+)'), ('near_mint', 'NM (9.0-9.2)'), ('very_fine_near_mint', 'VF/NM (8.0-9.0)'), ('very_fine', 'VF (7.0-8.0)'), ('fine_very_fine', 'F/VF (6.0-7.0)'), ('fine', 'Fine (5.0-6.0)'), ('very_good_fine', 'VG/F (4.0-5.0)'), ('very_good', 'VG (3.0-4.0)'), ('good', 'Good (1.8-3.0)'), ('fair', 'Fair (1.0-1.8)'), ('poor', 'Poor (0.5-1.0)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='ebay_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='validation_status',
            field=models.CharField(choices=[('unvalidated', 'Unvalidated'), ('enriched', 'Enriched'), ('verified', 'Verified')], default='unvalidated', max_length=20),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='condition',
            field=models.CharField(blank=True, choices=[('near_mint_mint', 'NM/M (9.2+)'), ('near_mint', 'NM (9.0-9.2)'), ('very_fine_near_mint', 'VF/NM (8.0-9.0)'), ('very_fine', 'VF (7.0-8.0)'), ('fine_very_fine', 'F/VF (6.0-7.0)'), ('fine', 'Fine (5.0-6.0)'), ('very_good_fine', 'VG/F (4.0-5.0)'), ('very_good', 'VG (3.0-4.0)'), ('good', 'Good (1.8-3.0)'), ('fair', 'Fair (1.0-1.8)'), ('poor', 'Poor (0.5-1.0)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='ebay_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='validation_status',
            field=models.CharField(choices=[('unvalidated', 'Unvalidated'), ('enriched', 'Enriched'), ('verified', 'Verified')], default='unvalidated', max_length=20),
        ),
        migrations.AlterField(
            model_name='startrekdccomic',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starwarsdarkhorsecomic',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starwarsmarvelcomic',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
