# Generated by Django 4.2.16 on 2026-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_books', '0004_startrekdccomic_inventory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startrekdccomic',
            name='weight_lbs',
            field=models.IntegerField(default=0, help_text='Weight - pounds'),
        ),
        migrations.AddField(
            model_name='startrekdccomic',
            name='weight_oz',
            field=models.IntegerField(default=0, help_text='Weight - ounces'),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='weight_lbs',
            field=models.IntegerField(default=0, help_text='Weight - pounds'),
        ),
        migrations.AddField(
            model_name='starwarsdarkhorsecomic',
            name='weight_oz',
            field=models.IntegerField(default=0, help_text='Weight - ounces'),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='weight_lbs',
            field=models.IntegerField(default=0, help_text='Weight - pounds'),
        ),
        migrations.AddField(
            model_name='starwarsmarvelcomic',
            name='weight_oz',
            field=models.IntegerField(default=0, help_text='Weight - ounces'),
        ),
    ]
