version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -t 30 -- 
             python manage.py makemigrations --noinput &&
             python manage.py migrate --run-syncdb &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    env_file:
      - ./samscollectibles/.env.local
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    env_file:
      - ./samscollectibles/.env.local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: