"""
Sam's Collectibles - eBay Automation Configuration
All paths, categories, eBay settings, and defaults in one place.
"""

import os
from pathlib import Path

# =============================================================================
# BASE PATHS
# =============================================================================

# Root of Sam's project folder
PROJECT_ROOT = Path(__file__).parent.parent

# Photos organized by product type / franchise
UPLOADS_DIR = PROJECT_ROOT / "ebay_uploads"

# HTML listing descriptions (generated by ebay-html-builder skill)
DESCRIPTIONS_DIR = PROJECT_ROOT / "ebay_descriptions"

# Historical CSVs (templates, reports, past uploads)
CSVS_DIR = PROJECT_ROOT / "csvs"

# Automation working directories
AUTOMATION_DIR = Path(__file__).parent
DATA_DIR = AUTOMATION_DIR / "data"
TEMPLATES_DIR = AUTOMATION_DIR / "templates"
OUTPUT_DIR = AUTOMATION_DIR / "output"

# =============================================================================
# UPLOADS FOLDER MAPPING
# =============================================================================
# Maps the upload folder names to product types and the corresponding
# descriptions subfolder structure.

UPLOAD_FOLDER_MAP = {
    "NS-Boxes": {
        "product_type": "boxes",
        "description_path": "ns-cards/boxes",
    },
    "NS-Packs": {
        "product_type": "packs",
        "description_path": "ns-cards/packs",
    },
    "NS-cvs-sets": {
        "product_type": "sets",
        "description_path": "ns-cards/sets",
    },
    "NS-Singles": {
        "product_type": "singles",
        "description_path": "ns-cards/singles",
    },
    "NS-Binders": {
        "product_type": "binders",
        "description_path": "ns-cards/binders",
    },
}

# =============================================================================
# FRANCHISE FOLDER MAPPING
# =============================================================================
# Maps folder names in ebay_uploads to their franchise slug used in
# ebay_descriptions. Case-insensitive matching.

FRANCHISE_MAP = {
    # Star Wars
    "Star Wars": "starwars",
    "sw-first_anthology": "starwars",
    "sw-shadows-of-the-empire": "starwars",
    "sw-trilogy-merlin": "starwars",
    "sw_3D": "starwars",
    "sw_anh": "starwars",
    "sw_mastervisions": "starwars",
    "sw_topps_trilogy_regular": "starwars",
    "sw_wonder_bread": "starwars",
    "SW-ROTJ-stickers": "starwars",

    # Star Trek
    "Star Trek": "startrek",

    # Movies
    "007-Goldeneye": "movies",
    "007-Moonraker": "movies",
    "007-TomorrowNeverDies": "movies",
    "Godzilla Green 1998": "movies",

    # TV Shows
    "Space 1999": "tv",
    "The Outer Limits": "tv",
    "x-file-s3": "tv",
    "x-files-contact": "tv",
    "x-files-s1": "tv",
    "x-files-s2": "tv",
    "x-files-showcase": "tv",

    # Comic Book properties
    "Marvel": "comicbooks",
    "Valiant": "comicbooks",
    "The Creators Universe": "comicbooks",

    # Other franchises (get their own folder)
    "Dune": "dune",
    "WizardOfOz-DuoCards": "wizard-of-oz",
    "WizardOfOz-Pacific": "wizard-of-oz",
    "DisneyCollectorCards2SkyBox92": "disney",
    "DisneyCollectorCardsImpel91": "disney",
    "CosmicCardsInauguralImpel": "cosmic-cards",
}

# =============================================================================
# EBAY CATEGORY NUMBERS
# =============================================================================

CATEGORY_MAP = {
    "boxes": "261035",       # Sealed Trading Card Boxes
    "packs": "183053",       # Sealed Trading Card Packs
    "sets": "183052",        # Trading Card Sets
    "singles": "183054",     # Individual Trading Cards
    "binders": "183052",     # Trading Card Sets (closest match)
    "comic_books": "259104", # Comics & Graphic Novels
    "posters": "261068",     # Posters
}

# =============================================================================
# EBAY CONDITION IDS
# =============================================================================

CONDITION_MAP = {
    "new_sealed": "7000",    # New/Factory Sealed
    "like_new": "6000",      # Like New
    "very_good": "5000",     # Very Good
    "good": "4000",          # Good
    "acceptable": "3000",    # Acceptable
}

# Default condition for sealed boxes
DEFAULT_CONDITION_ID = "7000"  # New/Factory Sealed

# =============================================================================
# EBAY LISTING DEFAULTS
# =============================================================================

LISTING_DEFAULTS = {
    "format": "FixedPrice",
    "duration": "GTC",       # Good 'Til Cancelled
    "quantity": "1",
    "currency": "USD",
    "location": "Piru, CA 93040",
    "country": "US",
    "site_id": "US",
    "condition_id": DEFAULT_CONDITION_ID,
    "immediate_pay": "true",
}

# =============================================================================
# SHIPPING DEFAULTS
# =============================================================================

SHIPPING_DEFAULTS = {
    "shipping_type": "Flat",
    "shipping_service_1": "USPSPriority",
    "shipping_cost_1": "0",           # Free shipping (or set a price)
    "dispatch_time_max": "3",         # Ships within 3 business days
}

# =============================================================================
# RETURN POLICY DEFAULTS
# =============================================================================

RETURN_DEFAULTS = {
    "returns_accepted": "ReturnsAccepted",
    "returns_within": "Days_30",
    "refund_option": "MoneyBack",
    "shipping_cost_paid_by": "Buyer",
}

# =============================================================================
# ITEM SPECIFICS DEFAULTS
# =============================================================================

ITEM_SPECIFICS_DEFAULTS = {
    "C:Language": "English",
    "C:Country of Origin": "United States",
    "C:Material": "Card Stock",
    "C:Vintage": "Yes",
}

# =============================================================================
# EBAY API CONFIGURATION
# =============================================================================

# Get a free API key at: https://developer.ebay.com
# Store as environment variable for security, or set directly here.
EBAY_APP_ID = os.environ.get("EBAY_APP_ID", "")
EBAY_API_ENVIRONMENT = "production"  # "sandbox" for testing

# Finding API settings
FINDING_API_ENDPOINT = "https://svcs.ebay.com/services/search/FindingService/v1"
MAX_SOLD_RESULTS = 50       # Max completed items to check per query
PRICE_CACHE_DAYS = 7        # Re-query after this many days

# =============================================================================
# CSV TEMPLATE
# =============================================================================

# Path to the eBay category listing template
CSV_TEMPLATE_PATH = CSVS_DIR / "eBay-category-listing-template-Oct-27-2025-10-15-47.csv"

# Path to the most recent active listings report
ACTIVE_LISTINGS_PATH = CSVS_DIR / "eBay-all-active-listings-report-2026-04-03-13292624172.csv"

# =============================================================================
# OUTPUT SETTINGS
# =============================================================================

# Generated CSV files go here
CSV_OUTPUT_DIR = OUTPUT_DIR
