"""
Sam's Collectibles - eBay Automation Configuration
All paths, categories, eBay settings, and defaults in one place.
"""

import os
from pathlib import Path

# =============================================================================
# BASE PATHS
# =============================================================================

# Root of Sam's project folder
PROJECT_ROOT = Path(__file__).parent.parent

# Photos organized by product type / franchise
UPLOADS_DIR = PROJECT_ROOT / "ebay_uploads"

# HTML listing descriptions (generated by ebay-html-builder skill)
DESCRIPTIONS_DIR = PROJECT_ROOT / "ebay_descriptions"

# Historical CSVs (templates, reports, past uploads)
CSVS_DIR = PROJECT_ROOT / "csvs"

# Automation working directories
AUTOMATION_DIR = Path(__file__).parent
DATA_DIR = AUTOMATION_DIR / "data"
TEMPLATES_DIR = AUTOMATION_DIR / "templates"
OUTPUT_DIR = AUTOMATION_DIR / "output"

# =============================================================================
# UPLOADS FOLDER MAPPING
# =============================================================================
# Maps the upload folder names to product types and the corresponding
# descriptions subfolder structure.

UPLOAD_FOLDER_MAP = {
    # Non-Sport Trading Cards
    "NS-Boxes": {
        "product_type": "boxes",
        "description_path": "ns-cards/boxes",
    },
    "NS-Packs": {
        "product_type": "packs",
        "description_path": "ns-cards/packs",
    },
    "NS-cvs-sets": {
        "product_type": "sets",
        "description_path": "ns-cards/sets",
    },
    "NS-Singles": {
        "product_type": "singles",
        "description_path": "ns-cards/singles",
    },
    "NS-Binders": {
        "product_type": "binders",
        "description_path": "ns-cards/binders",
    },
    "NS-Wrappers": {
        "product_type": "wrappers",
        "description_path": "ns-cards/wrappers",
    },
    # Movie Posters
    "Posters": {
        "product_type": "posters",
        "description_path": "posters",
    },
    # Comic Books
    "Comics-SW-Marvel": {
        "product_type": "comic_books",
        "description_path": "comic-books/starwars-marvel",
    },
    "Comics-SW-DarkHorse": {
        "product_type": "comic_books",
        "description_path": "comic-books/starwars-darkhorse",
    },
    "Comics-Other": {
        "product_type": "comic_books",
        "description_path": "comic-books/other",
    },
}

# =============================================================================
# FRANCHISE FOLDER MAPPING
# =============================================================================
# Maps folder names in ebay_uploads to their franchise slug used in
# ebay_descriptions. Case-insensitive matching.

FRANCHISE_MAP = {
    # Star Wars
    "Star Wars": "starwars",
    "sw-first_anthology": "starwars",
    "sw-shadows-of-the-empire": "starwars",
    "sw-trilogy-merlin": "starwars",
    "sw_3D": "starwars",
    "sw_anh": "starwars",
    "sw_mastervisions": "starwars",
    "sw_topps_trilogy_regular": "starwars",
    "sw_wonder_bread": "starwars",
    "SW-ROTJ-stickers": "starwars",

    # Star Trek
    "Star Trek": "startrek",

    # Movies
    "007-Goldeneye": "movies",
    "007-Moonraker": "movies",
    "007-TomorrowNeverDies": "movies",
    "Godzilla Green 1998": "movies",

    # TV Shows
    "Space 1999": "tv",
    "The Outer Limits": "tv",
    "x-file-s3": "tv",
    "x-files-contact": "tv",
    "x-files-s1": "tv",
    "x-files-s2": "tv",
    "x-files-showcase": "tv",

    # Comic Book properties (trading cards)
    "Marvel": "comicbooks",
    "Valiant": "comicbooks",
    "The Creators Universe": "comicbooks",

    # Posters
    "SW-Posters": "starwars",
    "Marvel-Posters": "marvel",
    "Movie-Posters": "movies",

    # Comics - Marvel Star Wars (1977-1986, #1-107)
    "SW-Marvel": "starwars",
    "complete-sets": "starwars",
    "key-issues": "starwars",
    "lots": "starwars",

    # Comics - Dark Horse Star Wars (1990s)
    "SW-DarkHorse": "starwars",
    "dark-empire": "starwars",
    "dark-empire-ii": "starwars",
    "crimson-empire": "starwars",
    "tales-of-the-jedi": "starwars",
    "shadows-of-the-empire": "starwars",
    "x-wing-rogue-squadron": "starwars",
    "classic-star-wars": "starwars",
    "other-series": "starwars",

    # Other franchises (get their own folder)
    "Dune": "dune",
    "WizardOfOz-DuoCards": "wizard-of-oz",
    "WizardOfOz-Pacific": "wizard-of-oz",
    "DisneyCollectorCards2SkyBox92": "disney",
    "DisneyCollectorCardsImpel91": "disney",
    "CosmicCardsInauguralImpel": "cosmic-cards",
}

# =============================================================================
# EBAY CATEGORY NUMBERS
# =============================================================================

CATEGORY_MAP = {
    "boxes": "261035",       # Sealed Trading Card Boxes
    "packs": "183053",       # Sealed Trading Card Packs
    "sets": "183052",        # Trading Card Sets
    "singles": "183054",     # Individual Trading Cards
    "binders": "183052",     # Trading Card Sets (closest match)
    "wrappers": "183054",    # Trading Card Wrappers
    "comic_books": "259104", # Comics & Graphic Novels
    "posters": "261068",     # Posters
}

# =============================================================================
# EBAY CONDITION IDS
# =============================================================================

CONDITION_MAP = {
    "new_sealed": "7000",    # New/Factory Sealed
    "like_new": "6000",      # Like New
    "very_good": "5000",     # Very Good
    "good": "4000",          # Good
    "acceptable": "3000",    # Acceptable
}

# Comic book grading → eBay condition ID mapping
COMIC_CONDITION_MAP = {
    "near_mint_mint": "7000",       # NM/M (9.2+)
    "near_mint": "7000",            # NM (9.0-9.2)
    "very_fine_near_mint": "6000",  # VF/NM (8.0-9.0)
    "very_fine": "5000",            # VF (7.0-8.0)
    "fine_very_fine": "4000",       # F/VF (6.0-7.0)
    "fine": "4000",                 # Fine (5.0-6.0)
    "very_good_fine": "3000",       # VG/F (4.0-5.0)
    "very_good": "3000",            # VG (3.0-4.0)
    "good": "3000",                 # Good (1.8-3.0)
    "fair": "3000",                 # Fair (1.0-1.8)
    "poor": "3000",                 # Poor (0.5-1.0)
}

# Default condition for sealed boxes
DEFAULT_CONDITION_ID = "7000"  # New/Factory Sealed

# =============================================================================
# EBAY LISTING DEFAULTS
# =============================================================================

LISTING_DEFAULTS = {
    "format": "FixedPrice",
    "duration": "GTC",       # Good 'Til Cancelled
    "quantity": "1",
    "currency": "USD",
    "location": "Piru, CA 93040",
    "country": "US",
    "site_id": "US",
    "condition_id": DEFAULT_CONDITION_ID,
    "immediate_pay": "true",
}

# =============================================================================
# SHIPPING DEFAULTS
# =============================================================================

SHIPPING_DEFAULTS = {
    "shipping_type": "Flat",
    "shipping_service_1": "USPSPriority",
    "shipping_cost_1": "0",           # Free shipping (or set a price)
    "dispatch_time_max": "3",         # Ships within 3 business days
}

# =============================================================================
# RETURN POLICY DEFAULTS
# =============================================================================

RETURN_DEFAULTS = {
    "returns_accepted": "ReturnsAccepted",
    "returns_within": "Days_30",
    "refund_option": "MoneyBack",
    "shipping_cost_paid_by": "Buyer",
}

# =============================================================================
# ITEM SPECIFICS DEFAULTS
# =============================================================================

ITEM_SPECIFICS_DEFAULTS = {
    "C:Language": "English",
    "C:Country of Origin": "United States",
    "C:Material": "Card Stock",
    "C:Vintage": "Yes",
}

# Comic book item specifics
COMIC_ITEM_SPECIFICS = {
    "C:Type": "Comic Book",
    "C:Country of Origin": "United States",
    "C:Language": "English",
}

# Poster item specifics
POSTER_ITEM_SPECIFICS = {
    "C:Type": "Poster",
    "C:Country of Origin": "United States",
}

# =============================================================================
# COMIC BOOK ERA CLASSIFICATION
# =============================================================================

COMIC_ERAS = {
    "golden_age": (1938, 1956),
    "silver_age": (1956, 1970),
    "bronze_age": (1970, 1984),
    "copper_age": (1984, 1991),
    "modern_age": (1992, 2099),
}

# =============================================================================
# COMIC PUBLISHERS
# =============================================================================

COMIC_PUBLISHERS = [
    "Marvel",
    "Dark Horse",
    "DC",
    "Image",
    "Valiant",
    "IDW",
]

# =============================================================================
# EBAY API CONFIGURATION
# =============================================================================

# Get a free API key at: https://developer.ebay.com
# Store these as environment variables in ~/.zshrc:
#   export EBAY_APP_ID="SamRoger-s-PRD-..."
#   export EBAY_DEV_ID="fdbd3909-..."
#   export EBAY_CERT_ID="PRD-..."
#   export EBAY_SANDBOX_APP_ID="SamRoger-s-SBX-..."
#   export EBAY_SANDBOX_CERT_ID="SBX-..."

EBAY_API_ENVIRONMENT = "production"  # "sandbox" for testing

# Production credentials
EBAY_PROD_APP_ID = os.environ.get("EBAY_APP_ID", "")
EBAY_PROD_DEV_ID = os.environ.get("EBAY_DEV_ID", "")
EBAY_PROD_CERT_ID = os.environ.get("EBAY_CERT_ID", "")

# Sandbox credentials
EBAY_SANDBOX_APP_ID = os.environ.get("EBAY_SANDBOX_APP_ID", "")
EBAY_SANDBOX_DEV_ID = os.environ.get("EBAY_DEV_ID", "")  # Same Dev ID for both
EBAY_SANDBOX_CERT_ID = os.environ.get("EBAY_SANDBOX_CERT_ID", "")

# Active credentials based on environment
if EBAY_API_ENVIRONMENT == "production":
    EBAY_APP_ID = EBAY_PROD_APP_ID
    EBAY_DEV_ID = EBAY_PROD_DEV_ID
    EBAY_CERT_ID = EBAY_PROD_CERT_ID
else:
    EBAY_APP_ID = EBAY_SANDBOX_APP_ID
    EBAY_DEV_ID = EBAY_SANDBOX_DEV_ID
    EBAY_CERT_ID = EBAY_SANDBOX_CERT_ID

# Finding API settings
FINDING_API_ENDPOINT = "https://svcs.ebay.com/services/search/FindingService/v1"
MAX_SOLD_RESULTS = 50       # Max completed items to check per query
PRICE_CACHE_DAYS = 7        # Re-query after this many days

# =============================================================================
# CSV TEMPLATE
# =============================================================================

# Path to the eBay category listing template
CSV_TEMPLATE_PATH = CSVS_DIR / "eBay-category-listing-template-Oct-27-2025-10-15-47.csv"

# Path to the most recent active listings report
ACTIVE_LISTINGS_PATH = CSVS_DIR / "eBay-all-active-listings-report-2026-04-03-13292624172.csv"

# =============================================================================
# OUTPUT SETTINGS
# =============================================================================

# Generated CSV files go here
CSV_OUTPUT_DIR = OUTPUT_DIR
